
import os
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem, QDesktopWidget
from PyQt5.QtCore import pyqtSlot
from sqlalchemy.sql import select
from sqlalchemy import func

from Penjualan.models import Akun, JenisBarang, Barang, DetailTransaksi, Transaksi
from Penjualan.database import engine, db_session


from Penjualan.akun import Ui_DialogAkun


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

class Ui_MainWindow(object):

    def __init__(self):
        self.MainWindow = QtWidgets.QMainWindow()
        self.setupUi(self.MainWindow)
        self.setCenter(self.MainWindow)
        
        
     
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(873, 600)
        font = QtGui.QFont()
        font.setPointSize(32)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(BASE_DIR,"images/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 81))
        self.frame_6.setStyleSheet("background-color: rgb(245, 121, 0);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Pothana2000")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.commandLinkButton_5 = QtWidgets.QCommandLinkButton(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Navilu")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.commandLinkButton_5.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(os.path.join(BASE_DIR,"images/log_out-2-512.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_5.setIcon(icon1)
        self.commandLinkButton_5.setIconSize(QtCore.QSize(32, 32))
        self.commandLinkButton_5.setObjectName("commandLinkButton_5")
        self.commandLinkButton_5.clicked.connect(self.logout)
        self.horizontalLayout.addWidget(self.commandLinkButton_5)
        self.gridLayout.addWidget(self.frame_6, 0, 0, 1, 5)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMaximumSize(QtCore.QSize(257, 16777215))
        self.frame_3.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnDashboard = QtWidgets.QCommandLinkButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Navilu")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btnDashboard.setFont(font)
        self.btnDashboard.setStyleSheet("color: rgb(211, 215, 207);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(os.path.join(BASE_DIR,"images/Home.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDashboard.setIcon(icon2)
        self.btnDashboard.setIconSize(QtCore.QSize(32, 32))
        self.btnDashboard.setObjectName("btnDashboard")
        self.verticalLayout.addWidget(self.btnDashboard)
        self.btnMaster = QtWidgets.QCommandLinkButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Navilu")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btnMaster.setFont(font)
        self.btnMaster.setStyleSheet("color: rgb(211, 215, 207);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(os.path.join(BASE_DIR,"images/icon-master-data-management.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMaster.setIcon(icon3)
        self.btnMaster.setIconSize(QtCore.QSize(32, 32))
        self.btnMaster.setObjectName("btnMaster")
        self.verticalLayout.addWidget(self.btnMaster)
        self.btnTransaksi = QtWidgets.QCommandLinkButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Navilu")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btnTransaksi.setFont(font)
        self.btnTransaksi.setStyleSheet("color: rgb(211, 215, 207);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(os.path.join(BASE_DIR,"images/transaction.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTransaksi.setIcon(icon4)
        self.btnTransaksi.setIconSize(QtCore.QSize(32, 32))
        self.btnTransaksi.setObjectName("btnTransaksi")
        self.verticalLayout.addWidget(self.btnTransaksi)
        self.btnAkun = QtWidgets.QCommandLinkButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Navilu")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btnAkun.setFont(font)
        self.btnAkun.setStyleSheet("\n"
"color: rgb(211, 215, 207);")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(os.path.join(BASE_DIR,"images/Utilities2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAkun.setIcon(icon5)
        self.btnAkun.setIconSize(QtCore.QSize(32, 32))
        self.btnAkun.setObjectName("btnAkun")
        self.verticalLayout.addWidget(self.btnAkun)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout.addWidget(self.frame_3, 1, 0, 4, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageDashboard = QtWidgets.QWidget()
        self.pageDashboard.setObjectName("pageDashboard")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.pageDashboard)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.scrollArea = QtWidgets.QScrollArea(self.pageDashboard)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 441, 170))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.toolButton = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.toolButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(os.path.join(BASE_DIR,"images/duit.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon6)
        self.toolButton.setIconSize(QtCore.QSize(64, 64))
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_5.addWidget(self.toolButton)
        self.toolButton_2 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_2.sizePolicy().hasHeightForWidth())
        self.toolButton_2.setSizePolicy(sizePolicy)
        self.toolButton_2.setStyleSheet("background-color: rgb(211, 215, 207);")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(os.path.join(BASE_DIR,"images/Analysis.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon7)
        self.toolButton_2.setIconSize(QtCore.QSize(64, 64))
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_5.addWidget(self.toolButton_2)
        self.toolButton_3 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_3.sizePolicy().hasHeightForWidth())
        self.toolButton_3.setSizePolicy(sizePolicy)
        self.toolButton_3.setStyleSheet("background-color: rgb(252, 175, 62);\n"
"background-color: rgb(211, 215, 207);")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(os.path.join(BASE_DIR,"images/Group2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon8)
        self.toolButton_3.setIconSize(QtCore.QSize(64, 64))
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout_5.addWidget(self.toolButton_3)
        self.gridLayout_7.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_8.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageDashboard)
        self.pageMaster = QtWidgets.QWidget()
        self.pageMaster.setObjectName("pageMaster")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pageMaster)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(1, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.txtCari_2 = QtWidgets.QLineEdit(self.pageMaster)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtCari_2.setFont(font)
        self.txtCari_2.setObjectName("txtCari_2")
        self.horizontalLayout_4.addWidget(self.txtCari_2)
        self.btnCari_2 = QtWidgets.QPushButton(self.pageMaster)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnCari_2.setFont(font)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(os.path.join(BASE_DIR,"images/Knob-Search-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCari_2.setIcon(icon9)
        self.btnCari_2.setIconSize(QtCore.QSize(24, 24))
        self.btnCari_2.setObjectName("btnCari_2")
        self.horizontalLayout_4.addWidget(self.btnCari_2)
        self.btnTambah = QtWidgets.QPushButton(self.pageMaster)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnTambah.setFont(font)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(os.path.join(BASE_DIR,"images/Knob-Add-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTambah.setIcon(icon10)
        self.btnTambah.setIconSize(QtCore.QSize(24, 24))
        self.btnTambah.setObjectName("btnTambah")
        self.btnTambah.clicked.connect(self.formTambahBarang)
        self.horizontalLayout_4.addWidget(self.btnTambah)
        self.comboBox = QtWidgets.QComboBox(self.pageMaster)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.pageMaster)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 593, 306))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableMaster = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_4)
        self.tableMaster.setObjectName("tableMaster")
        self.tableMaster.setColumnCount(7)
        self.tableMaster.setRowCount(0)
        self.tableMaster.cellDoubleClicked.connect(self.formBarang)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableMaster.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableMaster.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableMaster.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableMaster.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableMaster.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableMaster.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableMaster.setHorizontalHeaderItem(6, item)
        self.displayDataBarang()
        self.comboBox.currentTextChanged.connect(self.filterBarang)
        header = self.tableMaster.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(3, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(4, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(5, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(6, QtWidgets.QHeaderView.ResizeToContents)
        self.gridLayout_2.addWidget(self.tableMaster, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_2.addWidget(self.scrollArea_2)
        self.stackedWidget.addWidget(self.pageMaster)
        self.pageTransaksi = QtWidgets.QWidget()
        self.pageTransaksi.setObjectName("pageTransaksi")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.pageTransaksi)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem4, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.txtCariTransaksi = QtWidgets.QLineEdit(self.pageTransaksi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtCariTransaksi.sizePolicy().hasHeightForWidth())
        self.txtCariTransaksi.setSizePolicy(sizePolicy)
        self.txtCariTransaksi.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtCariTransaksi.setFont(font)
        self.txtCariTransaksi.setObjectName("txtCariTransaksi")
        self.horizontalLayout_2.addWidget(self.txtCariTransaksi)
        self.btnCariTransaksi = QtWidgets.QPushButton(self.pageTransaksi)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnCariTransaksi.setFont(font)
        self.btnCariTransaksi.setIcon(icon9)
        self.btnCariTransaksi.setIconSize(QtCore.QSize(24, 24))
        self.btnCariTransaksi.setObjectName("btnCariTransaksi")
        self.horizontalLayout_2.addWidget(self.btnCariTransaksi)
        self.comboBox_2 = QtWidgets.QComboBox(self.pageTransaksi)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.pageTransaksi)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 593, 306))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableTransaksi = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_5)
        self.tableTransaksi.setObjectName("tableTransaksi")
        self.tableTransaksi.setColumnCount(0)
        self.tableTransaksi.setRowCount(0)
        self.gridLayout_5.addWidget(self.tableTransaksi, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout_4.addWidget(self.scrollArea_3, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageTransaksi)
        self.pageAkun = QtWidgets.QWidget()
        self.pageAkun.setObjectName("pageAkun")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.pageAkun)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.txtCariAkun = QtWidgets.QLineEdit(self.pageAkun)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtCariAkun.sizePolicy().hasHeightForWidth())
        self.txtCariAkun.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtCariAkun.setFont(font)
        self.txtCariAkun.setObjectName("txtCariAkun")
        self.horizontalLayout_3.addWidget(self.txtCariAkun)
        self.btnCariAkun = QtWidgets.QPushButton(self.pageAkun)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCariAkun.sizePolicy().hasHeightForWidth())
        self.btnCariAkun.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnCariAkun.setFont(font)
        self.btnCariAkun.setIcon(icon9)
        self.btnCariAkun.setIconSize(QtCore.QSize(24, 24))
        self.btnCariAkun.setObjectName("btnCariAkun")
        self.horizontalLayout_3.addWidget(self.btnCariAkun)
        self.btnTambahAkun = QtWidgets.QPushButton(self.pageAkun)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTambahAkun.sizePolicy().hasHeightForWidth())
        self.btnTambahAkun.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnTambahAkun.setFont(font)
        self.btnTambahAkun.setIcon(icon10)
        self.btnTambahAkun.setIconSize(QtCore.QSize(24, 24))
        self.btnTambahAkun.setObjectName("btnTambahAkun")
        self.btnTambahAkun.clicked.connect(self.formTambahAkun)
        self.horizontalLayout_3.addWidget(self.btnTambahAkun)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem7, 0, 0, 1, 1)
        self.scrollArea_4 = QtWidgets.QScrollArea(self.pageAkun)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 593, 306))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tableAkun = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_6)
        self.tableAkun.setObjectName("tableAkun")
        self.tableAkun.setColumnCount(3)
        self.tableAkun.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableAkun.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableAkun.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableAkun.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.displayDataAkun()
        header = self.tableAkun.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)
        self.tableAkun.cellDoubleClicked.connect(self.formAkun)
        self.gridLayout_6.addWidget(self.tableAkun, 0, 0, 1, 1)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_6)
        self.gridLayout_3.addWidget(self.scrollArea_4, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageAkun)
        self.gridLayout.addWidget(self.stackedWidget, 4, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 873, 55))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.btnDashboard.clicked.connect(lambda:self.stackedWidget.setCurrentIndex(0))
        self.btnMaster.clicked.connect(lambda:self.stackedWidget.setCurrentIndex(1))
        self.btnAkun.clicked.connect(lambda:self.stackedWidget.setCurrentIndex(3))
        self.btnTransaksi.clicked.connect(lambda:self.stackedWidget.setCurrentIndex(2))

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Aplikasi Penjualan"))
        self.label.setText(_translate("MainWindow", "PT RESTU REESE"))
        self.commandLinkButton_5.setText(_translate("MainWindow", " Logout"))
        self.btnDashboard.setText(_translate("MainWindow", " Dashboard"))
        self.btnMaster.setText(_translate("MainWindow", " Master"))
        self.btnTransaksi.setText(_translate("MainWindow", " Transaksi"))
        self.btnAkun.setText(_translate("MainWindow", " Akun"))
        self.toolButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Omset Penjualan</p></body></html>"))
        self.toolButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Laporan Keuangan</p></body></html>"))
        self.toolButton_2.setText(_translate("MainWindow", "..."))
        self.toolButton_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>Performa Kasir</p></body></html>"))
        self.toolButton_3.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", "Do It Yourself"))
        self.btnCari_2.setText(_translate("MainWindow", "Cari"))
        self.btnTambah.setText(_translate("MainWindow", "Tambah"))
        self.comboBox.setItemText(0, _translate("MainWindow", "- Sorting Berdasarkan -"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Nama Barang"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Jenis Barang"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Stok"))
        self.btnCariTransaksi.setText(_translate("MainWindow", "Cari"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "- Sorting Berdasarkan -"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Kasir"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Barang"))
        self.btnCariAkun.setText(_translate("MainWindow", "Cari"))
        self.btnTambahAkun.setText(_translate("MainWindow", "Tambah"))
        item = self.tableAkun.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nama"))
        item = self.tableAkun.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Telepon"))
        item = self.tableAkun.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Username"))

        item = self.tableMaster.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Kode Barang"))
        item = self.tableMaster.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nama"))
        item = self.tableMaster.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Jenis Barang"))
        item = self.tableMaster.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Satuan"))
        item = self.tableMaster.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Harga Beli"))
        item = self.tableMaster.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Harga Jual"))
        item = self.tableMaster.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Stok"))

    def run(self):
        self.MainWindow.showMaximized()

    def setCenter(self,Form):
        qr = Form.frameGeometry()

        # center point of screen
        cp = QDesktopWidget().availableGeometry().center()

        # move rectangle's center point to screen's center point
        qr.moveCenter(cp)

        # top left of rectangle becomes top left of window centering it
        Form.move(qr.topLeft())

    def displayDataAkun(self):
        conn = engine.connect()
        s = select([Akun])
        result = conn.execute(s)
        rows = db_session.query(func.count(Akun.kode)).scalar()
        self.tableAkun.setRowCount(rows)
        for row, data in enumerate(result):
            nama = QTableWidgetItem(data[1])
            telepon = QTableWidgetItem(data[2])
            username = QTableWidgetItem(data[3])

            self.tableAkun.setItem(row,0,nama)
            self.tableAkun.setItem(row,1,telepon)
            self.tableAkun.setItem(row,2,username)

    def displayDataBarang(self):
        conn = engine.connect()
        s = select([Barang])
        result = conn.execute(s)
        rows = db_session.query(func.count(Barang.kode)).scalar()
        self.tableMaster.setRowCount(rows)
        for row, data in enumerate(result):
            kode = QTableWidgetItem(data[0])
            nama = QTableWidgetItem(data[1])
            jenis_barang = QTableWidgetItem(data[2])
            satuan = QTableWidgetItem(data[3])
            harga_beli = QTableWidgetItem(str(data[4]))
            harga_jual = QTableWidgetItem(str(data[5]))
            stok = QTableWidgetItem(str(data[6]))

            self.tableMaster.setItem(row,0,kode)
            self.tableMaster.setItem(row,1,nama)
            self.tableMaster.setItem(row,2,jenis_barang)
            self.tableMaster.setItem(row,3,satuan)
            self.tableMaster.setItem(row,4,harga_beli)
            self.tableMaster.setItem(row,5,harga_jual)
            self.tableMaster.setItem(row,6,stok)

    def formTambahAkun(self):
        akun = Ui_DialogAkun()
        akun.btnHapus.setEnabled(False)
        akun.btnEdit.setEnabled(False)
        akun.run()
        self.displayDataAkun()

    def logout(self):
        from Penjualan.loginadmin import Ui_DialogLogin
        login = Ui_DialogLogin()
        self.MainWindow.close()
        login.run()

    def formAkun(self):
        formakun = Ui_DialogAkun()
        username = self.tableAkun.item(self.tableAkun.currentRow(),2).text()
        akun = Akun.query.filter_by(username=username).first()
        formakun.txtKodeAkun.setText(akun.kode)
        formakun.txtNamaLengkap.setText(akun.nama)
        formakun.txtTelepon.setText(akun.telepon)
        formakun.txtUsername.setText(akun.username)
        formakun.txtPassword.setText(akun.password)
        formakun.btnTambah.setEnabled(False)
        formakun.run()
        self.displayDataAkun()

    def formTambahBarang(self):
        from Penjualan.barang import Ui_DialogBarang
        formbarang = Ui_DialogBarang()
        formbarang.btnEdit.setEnabled(False)
        formbarang.btnHapus.setEnabled(False)
        formbarang.run()
        self.displayDataBarang()

    def formBarang(self):
        from Penjualan.barang import Ui_DialogBarang
        kodeBarang = self.tableMaster.item(self.tableMaster.currentRow(),0).text()
        formbarang = Ui_DialogBarang()
        barang = Barang.query.filter_by(kode=kodeBarang).first()
        jenis_barang = JenisBarang.query.filter_by(kode=barang.jenis_barang).first()
        formbarang.kodeBarang.setText(barang.kode)
        formbarang.txtNamaBarang.setText(barang.nama)
        formbarang.txtSatuan.setText(str(barang.satuan))
        formbarang.txtHargaBeli.setText(str(barang.harga_beli))
        formbarang.txtHargaJual.setText(str(barang.harga_jual))
        formbarang.txtStok.setText(str(barang.stok))
        index = formbarang.cbJenisBarang.findText(jenis_barang.nama, QtCore.Qt.MatchFixedString)
        if index >= 0:
            formbarang.cbJenisBarang.setCurrentIndex(index)

        formbarang.btnTambah.setEnabled(False)
        formbarang.run()
        self.displayDataBarang()

    def filterBarang(self):
        key = self.comboBox.currentText()
        if key == "Nama Barang":
            datas = Barang.query.order_by(Barang.nama).all()
            for row, barang in enumerate(datas):
                data = Barang.query.filter_by(nama=str(barang)).first()
                kode = QTableWidgetItem(data.kode)
                nama = QTableWidgetItem(data.nama)
                jenis_barang = QTableWidgetItem(data.jenis_barang)
                satuan = QTableWidgetItem(data.satuan)
                harga_beli = QTableWidgetItem(str(data.harga_beli))
                harga_jual = QTableWidgetItem(str(data.harga_jual))
                stok = QTableWidgetItem(str(data.stok))

                self.tableMaster.setItem(row,0,kode)
                self.tableMaster.setItem(row,1,nama)
                self.tableMaster.setItem(row,2,jenis_barang)
                self.tableMaster.setItem(row,3,satuan)
                self.tableMaster.setItem(row,4,harga_beli)
                self.tableMaster.setItem(row,5,harga_jual)
                self.tableMaster.setItem(row,6,stok)

        elif key == "Jenis Barang":
            datas = Barang.query.order_by(Barang.jenis_barang).all()
            for row, barang in enumerate(datas):
                data = Barang.query.filter_by(nama=str(barang)).first()
                kode = QTableWidgetItem(data.kode)
                nama = QTableWidgetItem(data.nama)
                jenis_barang = QTableWidgetItem(data.jenis_barang)
                satuan = QTableWidgetItem(data.satuan)
                harga_beli = QTableWidgetItem(str(data.harga_beli))
                harga_jual = QTableWidgetItem(str(data.harga_jual))
                stok = QTableWidgetItem(str(data.stok))

                self.tableMaster.setItem(row,0,kode)
                self.tableMaster.setItem(row,1,nama)
                self.tableMaster.setItem(row,2,jenis_barang)
                self.tableMaster.setItem(row,3,satuan)
                self.tableMaster.setItem(row,4,harga_beli)
                self.tableMaster.setItem(row,5,harga_jual)
                self.tableMaster.setItem(row,6,stok)
        elif key == "Stok":
            datas = Barang.query.order_by(Barang.stok).all()
            for row, barang in enumerate(datas):
                data = Barang.query.filter_by(nama=str(barang)).first()
                kode = QTableWidgetItem(data.kode)
                nama = QTableWidgetItem(data.nama)
                jenis_barang = QTableWidgetItem(data.jenis_barang)
                satuan = QTableWidgetItem(data.satuan)
                harga_beli = QTableWidgetItem(str(data.harga_beli))
                harga_jual = QTableWidgetItem(str(data.harga_jual))
                stok = QTableWidgetItem(str(data.stok))

                self.tableMaster.setItem(row,0,kode)
                self.tableMaster.setItem(row,1,nama)
                self.tableMaster.setItem(row,2,jenis_barang)
                self.tableMaster.setItem(row,3,satuan)
                self.tableMaster.setItem(row,4,harga_beli)
                self.tableMaster.setItem(row,5,harga_jual)
                self.tableMaster.setItem(row,6,stok)
        else:
            self.displayDataBarang()